[package]
name = "presentation-manager-rs"
version = "0.1.0"
authors = ["mattdark"]

[dependencies]
rocket = "0.3.9"
rocket_codegen = "0.3.9"
crossbeam-deque = "0.3.0"
serde = "1.0.45"
serde_derive = "1.0.45"
serde_json = "1.0.17"
handlebars = "0.32.1"
cookie = "0.10.1"

[dependencies.rocket_contrib]
version = "0.3.9"
features = ["handlebars_templates"]

[lib]
name = "mylib"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/main.rs"
