[package]
name = "presentation-manager-rs"
version = "0.1.0"
authors = ["mattdark"]

[dependencies]
rocket = "0.3.8"
rocket_codegen = "0.3.8"
crossbeam-deque = "0.3.0"
serde = "1.0.42"
serde_derive = "1.0.42"
serde_json = "1.0.16"
handlebars = "0.32.0"

[dependencies.rocket_contrib]
version = "0.3.8"
features = ["handlebars_templates"]

[lib]
name = "mylib"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/main.rs"
