[global]
limits = { forms = 32768, json = 32768 }

[development]
address = "localhost"
port = "8000"
log = "normal"

[staging]
address = "0.0.0.0"
port = "8000"
log = "normal"

[production]
address = "https://reveal-gallery.herokuapp.com"
log = "critical"
