name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
      strategy:
        ubuntu:
          rust: [nightly]

    steps:
    - uses: mattdark/rust-action@master
      with:
        rust-version: ubuntu.rust
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
